export { Dialogue } from '@components/layouts/dialogue';
export type { DialogueProps } from '@components/layouts/dialogue';
export { Error } from '@components/layouts/error';
export type { ErrorProps } from '@components/layouts/error';
export { Page } from '@components/layouts/page';
export type { PageProps } from '@components/layouts/page';
export { PassportPage } from '@components/layouts/passport-page';
export type { PassportPageProps } from '@components/layouts/passport-page';
export { WalletPage } from '@components/layouts/wallet-page/';
export type { WalletPageProps } from '@components/layouts/wallet-page/';
