name: Publish

on:
  push:
    branches:
      - 'main'

env:
  GH_TOKEN: ${{ secrets.SVC_GIT_FG_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-20.04
    name: Publish
    permissions:
      contents: read
      id-token: write
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SVC_GIT_FG_TOKEN }}

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Unset header
        # https://github.com/intuit/auto/issues/1030
        run: git config --local --unset http.https://github.com/.extraheader

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Library Build
        run: pnpm lib:build

      - name: Create Labels
        run: pnpm auto create-labels

      - name: Create Release
        run: pnpm lib:publish
